### PR TITLE
Added navbar

### PR DESCRIPTION
**Pull request by artimanputra**
I have added a navbar. [See screenshot here](https://github.com/atharva0300/Meme-Generator/issues/7)

### CODE REVIEW

**Comment by subhangi2731** [comment]
@artimanputra can you please upload the screenshot here

**Comment by artimanputra** [comment]
> @artimanputra can you please upload the screenshot here
Screenshot (193)

**Comment by adityabisoi** [comment]
Can you check loading your extension once? It looks like this
Screenshot from 2021-12-08 09-21-35

**Comment by artimanputra** [comment]
> Can you check loading your extension once? It looks like this Screenshot from 2021-12-08 09-21-35

https://user-images.githubusercontent.com/79042027/145146918-709fa77b-c24d-4b4e-84a7-1bb24bf92882.mp4

It is like this on my PC

**Comment by subhangi2731** [comment]
@artimanputra Can you put different colours in navbar and body?

**Comment by artimanputra** [comment]
> @artimanputra Can you put different colors in navbar and body?

Yup. Let me know which colour will work? Shall I use dark colours?

**Comment by subhangi2731** [comment]
@artimanputra You can use grey color in the whole navbar also make the color hover on the links in the navbar(text) so that when you keep the mouse pointer and select it shows a different color and when you don't select it shows the normal navbar color. Keep the text color normally as grey but when selecting it as blue as you have kept it now

**Comment by artimanputra** [comment]
> @artimanputra You can use grey color in the whole navbar also make the color hover on the links in the navbar(text) so that when you keep the mouse pointer and select it shows a different color and when you don't select it shows the normal navbar color. Keep the text color normally as grey but when selecting it as blue as you have kept it now

okay

**Comment by artimanputra** [comment]
> @artimanputra You can use grey color in the whole navbar also make the color hover on the links in the navbar(text) so that when you keep the mouse pointer and select it shows a different color and when you don't select it shows the normal navbar color. Keep the text color normally as grey but when selecting it as blue as you have kept it now

Checkout This

https://user-images.githubusercontent.com/79042027/145157398-de3873e3-f2aa-48d5-8dfe-7a889fb3d718.mp4

**Comment by adityabisoi** [comment]
@artimanputra Did you load the extension?

**Comment by artimanputra** [comment]
> @artimanputra Did you load the extension?

Yes

**Comment by subhangi2731** [comment]
@artimanputra Great. Just one thing the area where you have written `save notes` text don't keep that part grey you can keep that blue just keep the navbar part grey where you have the links

**Comment by artimanputra** [comment]
> @artimanputra Great. Just one thing the area where you have written `save notes` text don't keep that part grey you can keep that blue just keep the navbar part grey where you have the links

@subhangi2731  Okay, check this once . @adityabisoi 
chrome_O3V3oN3qsx

**Comment by subhangi2731** [comment]
@artimanputra The extension doesn't load for me too

**Comment by artimanputra** [comment]
> @artimanputra The extension doesn't load for me too

okay will check once again

**Comment by adityabisoi** [comment]
@artimanputra Instead of opening the HTML page on a browser, try loading the extension following steps mentioned in README, then open the extension to see how your changes look.

**Comment by artimanputra** [comment]
> @artimanputra Instead of opening the HTML page on a browser, try loading the extension following steps mentioned in README, then open the extension to see how your changes look.

Okay

**Comment by adityabisoi** [comment]
@artimanputra Any updates on this?

**Comment by subhangi2731** [comment]
Hi @artimanputra Do you need some help on this?

**Comment by artimanputra** [comment]
> Hi @artimanputra Do you need some help on this?

Yeah, I am getting a lot of errors when I am trying to set up it locally. I have sent those screenshots on gitter.

**Comment by adityabisoi** [comment]
@artimanputra Since your queries in Gitter have been cleared now, can you provide updates on this issue?

**Comment by artimanputra** [comment]
> @artimanputra Since your queries in Gitter have been cleared now, can you provide updates on this issue?

@adityabisoi yup I am on that, just tell me Shall I create a new component for the header? and one more thing there is no app.js or index.js so in which should I import it?

**Comment by adityabisoi** [comment]
> > @artimanputra Since your queries in Gitter have been cleared now, can you provide updates on this issue?
> 
> @adityabisoi yup I am on that, just tell me Shall I create a new component for the header? and one more thing there is no app.js or index.js so in which should I import it?

This is not a React-based project. You cannot create components/import/export them. You can work on the popup.html and CSS files for the extension and then load it  in the browser as mentioned to check your changes.

**Comment by artimanputra** [comment]
> > @artimanputra Since your queries in Gitter has been cleared now, can you provide updates on this issue?
> 
> @adityabisoi yup I am on that, just tell me Shall I create a new component for the header? and one more thing there is no app.js or index.js so in which should I import it? Like last time I have added It in the popup.html but it's not loading.

**Comment by artimanputra** [comment]
> > > @artimanputra Since your queries in Gitter have been cleared now, can you provide updates on this issue?
> > 
> > 
> > @adityabisoi yup I am on that, just tell me Shall I create a new component for the header? and one more thing there is no app.js or index.js so in which should I import it?
> 
> This is not a React-based project. You cannot create components/import/export them. You can work on the popup.html and CSS files for the extension and then load it in the browser as mentioned to check your changes.

 Ohkay

**Comment by subhangi2731** [comment]
@artimanputra were you able to do this please let me know

**Comment by artimanputra** [comment]
> @artimanputra were you able to do this please let me know
@subhangi2731  I have done the changes and now it's loading in the extension, so please check once.

https://user-images.githubusercontent.com/79042027/147353730-b8194dde-17b7-417b-87c0-1c33eaedf18b.mp4

**Pull request merged**
