### PR TITLE
Added the layout for the extension

### PR DESCRIPTION
**Pull request by Palash1999**
Added all the required files for the extension including icons, displaying "Hello World!".

### CODE REVIEW

**Comment by adityabisoi** [comment]
@Palash1999 You have not added the background script. Also, create a different folder for the CSS. 
Create `src` folder with `views` containing templates and `styles` folder containing the CSS.

**Comment by Palash1999** [comment]
Ok, I will update it.

**Comment by Palash1999** [comment]
Updated, please let me know if I did something wrong.

**Comment by adityabisoi** [comment]
@Palash1999 Let's not use Jquery for now. Use vanilla javascript, and add a background script. Refer to the resources provided for more details.

**Comment by Palash1999** [comment]
Done👍

**Pull request merged**
